### ISSUE TITLE
Minor issues with React and padding (and thanks!)

### ISSUE THREAD

**Issue by alfonsomunozpomer** [terrymun/StickySort#1]
Hi, I just wanted to let you know that we had this same problem in [our project, the Expression Atlas](http://www.ebi.ac.uk/gxa/), and this plug-in, especially [your post and explanation](http://tympanus.net/codrops/2014/01/09/sticky-table-headers-columns/), helped us a lot. Following your strategy we have now a fully-working solution. However, we can’t use your plug-in straight out of the box for the following reasons:
1. We have a fixed element to the top of the page, right before the table, with hcSticky, so the sticky header needs to be positioned according to the padding of the div that contains the table.
2. We build our table with React and we have a button in the intersect, therefore, if we clone it with jQuery we get a React invariant violation.

These are, I suppose, very two edge cases. React more so than the padding thing, but I think it was worth mentioning them.

At the moment the changes aren’t live yet, but I’ll post a follow-up message when we do. A very big thank you is in order.

**Comment by terrymun** [comment]
Hi @alfonsomunozpomer,

Thanks for letting me know! Actually your implementation got me a bit excited, since I'm a molecular biologist myself, work on gene expression analysis and also uses the Expression Atlas every now and then. I'm delighted that I can contribute back to a resource that I've used ever so often!

Indeed, the sticky header plugin has some restrictions in the sense that it does not take into account other elements that have fixed positions relative to the viewport. However, it seems like you guys managed to circumvent it by simply manipulating (by addition) the computed value of the sticky row header.

I am, however, unfamiliar with React.js, but if you're using event handlers you can always use jQuery's `.on()` method to bind events to elements that might be dynamically added.

**Comment by alfonsomunozpomer** [comment]
Hi Terry. So you’re a molecular biologist. That’s certainly a surprise. :)

Our implementation of the sticky header following more or less your post went live. You can see it working on any experiment, but on the wide ones is where it really shines:
http://www.ebi.ac.uk/gxa/experiments/E-MTAB-2836

Regarding React, the problem we had is that for every HTML element declared inside a React component it generates a `data-reactid` field (e.g. `<div ... data-reactid=".0.1.0.0.1.0" ...>`) and these ids need to be unique for React to do its magic. It has a virtual DOM in memory which it uses to compute the deltas with the actual DOM so it only re-renders the necessary elements. Cloning the element with jQuery creates another element with the same id and React complains. The solution in our case involved creating the header within the React component so that it assigned it a valid `data-reactid`. Additionally, because our headers are interactive we needed to share the state between the two headers in the table, but that is usual React practice.

Another issue we had is that [our leftmost column in the header, in some cases, contains a radio button group](http://www.ebi.ac.uk/gxa/experiments/E-MTAB-2836?geneQuery=ENSG00000197249), which means that cloning the element creates three more radio buttons with the same `value` and `name` fields which we needed to change within React as well.

Again, thank you for sharing your work.

P.S.: The sticky column will be coming in the near future. ;)
